<?php

return [
    "Cada día es una oportunidad para ser mejor que ayer.",
    "No te detengas, estás más cerca de lo que crees.",
    "El cambio empieza cuando decides no rendirte.",
    "Tu futuro depende de lo que hagas hoy.",
    "Crecer duele, pero quedarse igual duele más.",
    "No eres el mismo de ayer, sigue avanzando.",
    "Los pequeños pasos también son progreso.",
    "La disciplina crea la vida que la motivación no puede.",
    "No busques ser perfecto, busca ser constante.",
    "Todo avance cuenta, aunque sea lento.",
    "Lo difícil también te está formando.",
    "Si no te reta, no te cambia.",
    "La versión que quieres ser requiere esfuerzo.",
    "No te compares, compite contigo mismo.",
    "El progreso es silencioso, pero poderoso.",
    "Lo que hoy te cuesta, mañana será tu fortaleza.",
    "Cada intento te acerca más.",
    "No es magia, es constancia.",
    "Cambia tus hábitos y cambiará tu vida.",
    "El crecimiento empieza fuera de la comodidad.",
    "No te rindas solo porque es difícil.",
    "Eres capaz de más de lo que imaginas.",
    "Hazlo aunque no tengas ganas.",
    "Tu esfuerzo de hoy es tu resultado de mañana.",
    "Nada cambia si tú no cambias.",
    "La paciencia también es progreso.",
    "Sigue aunque nadie lo note.",
    "El fracaso solo es parte del proceso.",
    "Cada error te hace más fuerte.",
    "No estás atrasado, estás en proceso.",
    "La constancia vence al talento sin disciplina.",
    "Tu única competencia eres tú mismo.",
    "No pares hasta sentir orgullo.",
    "Lo que hoy parece lento, mañana será avance.",
    "Confía en el proceso, no en la rapidez.",
    "Hazlo con miedo, pero hazlo.",
    "La acción vence a la duda.",
    "No esperes motivación, crea disciplina.",
    "Tu crecimiento no es visible todos los días.",
    "Todo esfuerzo tiene recompensa.",
    "No te conformes con poco si puedes más.",
    "El dolor de crecer es temporal.",
    "Cada día estás construyendo tu futuro.",
    "Sigue, aunque sea difícil.",
    "Lo imposible solo tarda más.",
    "El cambio comienza contigo.",
    "No te rindas en el proceso.",
    "La perseverancia lo cambia todo.",
    "Cada día cuenta, no lo desperdicies.",
    "Sigue creciendo, tu mejor versión te espera.",
    "Hoy sonríe, alguien necesita tu energía positiva.",
    "Recuerda comer bien, también cuidas vidas cuando te cuidas tú.",
    "Tus enseñanzas marcan vidas más de lo que imaginas.",
    "Cada alumno que pasa por ti deja una huella en tu historia.",
    "Descansa, también enseñar es un acto de equilibrio.",
    "Tu paciencia construye futuros.",
    "Un buen maestro enseña con el corazón, no solo con la voz.",
    "Hoy puedes ser la razón de la inspiración de alguien.",
    "Lo que dices hoy puede cambiar una vida mañana.",
    "Respira, estás haciendo un gran trabajo.",
    "Tu esfuerzo diario vale más de lo que ves.",
    "Enseñar es sembrar sin saber cuándo se cosecha.",
    "Cuida tu mente, también eres importante.",
    "Tu vocación deja huellas invisibles pero eternas.",
    "Hoy puede ser un gran día para inspirar.",
    "No todos los héroes llevan capa, algunos llevan libros.",
    "Gracias por no rendirte con cada alumno.",
    "Tu energía en el aula cambia el ambiente.",
    "Un buen maestro enseña incluso en silencio.",
    "También mereces paciencia contigo mismo.",
    "Cada clase es una oportunidad para impactar vidas.",
    "Tu voz puede ser el impulso que alguien necesita.",
    "No subestimes el valor de tu trabajo.",
    "Hoy puedes inspirar más de lo que crees.",
    "Eres parte del futuro de muchos.",
    "Tu vocación es un regalo para el mundo.",
    "Los pequeños avances también son grandes logros.",
    "Enseñar también es aprender todos los días.",
    "Tu dedicación construye más de lo visible.",
    "Tómate un momento para ti, también lo mereces.",
    "Tu enseñanza puede durar toda una vida en alguien.",
    "Eres guía, apoyo y ejemplo.",
    "Hoy puede ser difícil, pero sigues haciendo la diferencia.",
    "Cada alumno es una historia que ayudaste a escribir.",
    "No todos los días serán fáciles, pero todos valen.",
    "Tu trabajo tiene un impacto que no siempre ves.",
    "Sigue, incluso cuando no lo notes.",
    "Un maestro feliz enseña mejor.",
    "Tu vocación transforma el mundo poco a poco.",
    "Hoy alguien aprendió gracias a ti.",
    "También mereces reconocimiento por lo que haces.",
    "La enseñanza empieza en el ejemplo.",
    "Tu esfuerzo no pasa desapercibido.",
    "Eres parte del cambio de muchas vidas.",
    "Tu paciencia es una forma de amor.",
    "Descansa, mañana seguirás cambiando vidas.",
    "Tu presencia en el aula importa más de lo que crees.",
    "Enseñar es dejar luz en otros.",
    "Tu labor construye el futuro sin que lo notes.",
    "Gracias por enseñar con el corazón.",
    "Recuerda comer bien hoy.",
    "Recuerda beber agua.",
    "Recuerda sentarte bien.",
    "Levántate y estira un poco.",
    "Respira profundo, todo está bien.",
    "Tómate un descanso.",
    "Ya bebiste agua hoy?",
    "Cuida tu postura.",
    "Descansa tus ojos un momento.",
    "Come algo saludable.",

    "No olvides moverte un poco.",
    "Relaja tus hombros.",
    "Haz una pausa.",
    "El café es vida… ¿ya tomaste el tuyo?",
    "Recuerda hidratarte.",
    "Sonríe un poco, ayuda más de lo que crees.",
    "No te saltes comidas.",
    "Estira tu espalda.",
    "Toma aire fresco.",
    "Desconéctate un momento.",

    "Cuida tu cuerpo, es tu casa.",
    "Descansa la mente.",
    "Come sin prisa.",
    "Bebe un vaso de agua ahora.",
    "Corrige tu postura.",
    "Haz una pausa activa.",
    "Recuerda parpadear.",
    "No olvides desayunar bien.",
    "Tu cuerpo necesita descanso.",
    "Muévete un poco.",

    "Relaja tu cuello.",
    "Toma un respiro profundo.",
    "Hidrátate, es importante.",
    "No te sobrecargues hoy.",
    "Cuida tu energía.",
    "Pausa y continúa después.",
    "Come algo ligero si puedes.",
    "Escucha a tu cuerpo.",
    "Haz una pausa corta.",
    "Tu bienestar importa.",

    "Recuerda estirarte cada cierto tiempo.",
    "No olvides beber agua otra vez.",
    "Descansa aunque sea un minuto.",
    "Respira y sigue.",
    "El cuerpo también necesita descanso.",
    "Hazlo a tu ritmo.",
    "No olvides cuidar tu postura al sentarte.",
    "Un pequeño descanso hace la diferencia.",
    "Tu salud es prioridad.",
    "Recuerda: estás haciendo lo mejor que puedes."
];
